"""
Pydantic schemas for Persian Social Analytics.
"""

from app.schemas.base import (
    BaseSchema,
    TimestampSchema,
    IDSchema,
    PaginationParams,
    PaginatedResponse,
    MessageResponse,
    ErrorResponse,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserUpdatePassword,
    UserInDB,
    UserResponse,
    UserBrief,
)
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    TokenPayload,
    RefreshTokenRequest,
    AuthResponse,
)
from app.schemas.data_source import (
    DataSourceBase,
    DataSourceCreate,
    DataSourceUpdate,
    DataSourceResponse,
    DataSourceBrief,
    DataSourceStats,
)
from app.schemas.author import (
    AuthorBase,
    AuthorCreate,
    AuthorUpdate,
    AuthorResponse,
    AuthorBrief,
    AuthorWithMetrics,
)
from app.schemas.post import (
    PostBase,
    PostCreate,
    PostUpdate,
    PostResponse,
    PostWithRelations,
    PostBrief,
    PostBulkCreate,
    PostFilter,
)
from app.schemas.analysis import (
    AnalysisBase,
    AnalysisCreate,
    AnalysisUpdate,
    AnalysisResponse,
    AnalysisWithUser,
    AnalysisBrief,
    AnalysisConfig,
    AnalysisProgress,
    AnalysisSubmit,
)
from app.schemas.analysis_result import (
    SentimentResult,
    EmotionResult,
    EntityResult,
    TopicResult,
    AnalysisResultBase,
    AnalysisResultCreate,
    AnalysisResultResponse,
    AnalysisResultWithPost,
    AnalysisSummary,
    BulkResultCreate,
)
from app.schemas.trend import (
    TrendBase,
    TrendCreate,
    TrendUpdate,
    TrendResponse,
    TrendWithDetails,
    TrendBrief,
    TrendingItem,
)
from app.schemas.graph import (
    GraphNodeBase,
    GraphNodeCreate,
    GraphNodeUpdate,
    GraphNodeResponse,
    GraphEdgeBase,
    GraphEdgeCreate,
    GraphEdgeResponse,
    GraphData,
    GraphStats,
    CommunityInfo,
    PageRankResult,
    GraphAnalysisRequest,
)
from app.schemas.dashboard import (
    WidgetConfig,
    DashboardBase,
    DashboardCreate,
    DashboardUpdate,
    DashboardResponse,
    DashboardBrief,
    WidgetData,
)
from app.schemas.brain import (
    BrainHealthResponse,
    TextAnalysisRequest,
    TextAnalysisResponse,
    BatchAnalysisRequest,
    BatchAnalysisResponse,
    GraphAnalysisRequest as BrainGraphRequest,
    GraphAnalysisResponse as BrainGraphResponse,
    SummarizationRequest,
    TrendDetectionRequest,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema",
    "IDSchema",
    "PaginationParams",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserUpdatePassword",
    "UserInDB",
    "UserResponse",
    "UserBrief",
    # Auth
    "LoginRequest",
    "TokenResponse",
    "TokenPayload",
    "RefreshTokenRequest",
    "AuthResponse",
    # DataSource
    "DataSourceBase",
    "DataSourceCreate",
    "DataSourceUpdate",
    "DataSourceResponse",
    "DataSourceBrief",
    "DataSourceStats",
    # Author
    "AuthorBase",
    "AuthorCreate",
    "AuthorUpdate",
    "AuthorResponse",
    "AuthorBrief",
    "AuthorWithMetrics",
    # Post
    "PostBase",
    "PostCreate",
    "PostUpdate",
    "PostResponse",
    "PostWithRelations",
    "PostBrief",
    "PostBulkCreate",
    "PostFilter",
    # Analysis
    "AnalysisBase",
    "AnalysisCreate",
    "AnalysisUpdate",
    "AnalysisResponse",
    "AnalysisWithUser",
    "AnalysisBrief",
    "AnalysisConfig",
    "AnalysisProgress",
    "AnalysisSubmit",
    # AnalysisResult
    "SentimentResult",
    "EmotionResult",
    "EntityResult",
    "TopicResult",
    "AnalysisResultBase",
    "AnalysisResultCreate",
    "AnalysisResultResponse",
    "AnalysisResultWithPost",
    "AnalysisSummary",
    "BulkResultCreate",
    # Trend
    "TrendBase",
    "TrendCreate",
    "TrendUpdate",
    "TrendResponse",
    "TrendWithDetails",
    "TrendBrief",
    "TrendingItem",
    # Graph
    "GraphNodeBase",
    "GraphNodeCreate",
    "GraphNodeUpdate",
    "GraphNodeResponse",
    "GraphEdgeBase",
    "GraphEdgeCreate",
    "GraphEdgeResponse",
    "GraphData",
    "GraphStats",
    "CommunityInfo",
    "PageRankResult",
    "GraphAnalysisRequest",
    # Dashboard
    "WidgetConfig",
    "DashboardBase",
    "DashboardCreate",
    "DashboardUpdate",
    "DashboardResponse",
    "DashboardBrief",
    "WidgetData",
    # Brain
    "BrainHealthResponse",
    "TextAnalysisRequest",
    "TextAnalysisResponse",
    "BatchAnalysisRequest",
    "BatchAnalysisResponse",
    "BrainGraphRequest",
    "BrainGraphResponse",
    "SummarizationRequest",
    "TrendDetectionRequest",
]
